---

- name: "tasks dnsdist-build"
  include: "dnsdist-build.yml"
  tags:
    - dnsdist-build
#  when: dnsdist_version != '1.8.0'

#- name: "tasks dnsdist-build-1.8"
#  include: "dnsdist-build-1.8.yml"
#  tags:
#    - dnsdist-build
#  when: dnsdist_version == '1.8.0'

#- name: "tasks dnsdist-sw-version"
#  include: "dnsdist-sw-version.yml"
#  tags:
#    - dnsdist-sw-version

#- name: "tasks dnsdist-configs"
#  include: "dnsdist-configs.yml"
#  tags:
#    - dnsdist-configs
##  when: dnsdist_version != '1.8.0'

